// Team and League Logo URLs Database

const TEAM_LOGO_URLS = {
    // NHL Teams (all 32)
    "Anaheim Ducks": "https://assets.nhle.com/logos/nhl/svg/ANA_dark.svg",
    "Boston Bruins": "https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg",
    "Buffalo Sabres": "https://assets.nhle.com/logos/nhl/svg/BUF_dark.svg",
    "Calgary Flames": "https://assets.nhle.com/logos/nhl/svg/CGY_dark.svg",
    "Carolina Hurricanes": "https://assets.nhle.com/logos/nhl/svg/CAR_dark.svg",
    "Chicago Blackhawks": "https://assets.nhle.com/logos/nhl/svg/CHI_dark.svg",
    "Colorado Avalanche": "https://assets.nhle.com/logos/nhl/svg/COL_dark.svg",
    "Columbus Blue Jackets": "https://assets.nhle.com/logos/nhl/svg/CBJ_dark.svg",
    "Dallas Stars": "https://assets.nhle.com/logos/nhl/svg/DAL_dark.svg",
    "Detroit Red Wings": "https://assets.nhle.com/logos/nhl/svg/DET_dark.svg",
    "Edmonton Oilers": "https://assets.nhle.com/logos/nhl/svg/EDM_dark.svg",
    "Florida Panthers": "https://assets.nhle.com/logos/nhl/svg/FLA_dark.svg",
    "Los Angeles Kings": "https://assets.nhle.com/logos/nhl/svg/LAK_dark.svg",
    "Minnesota Wild": "https://assets.nhle.com/logos/nhl/svg/MIN_dark.svg",
    "Montreal Canadiens": "https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg",
    "Nashville Predators": "https://assets.nhle.com/logos/nhl/svg/NSH_dark.svg",
    "New Jersey Devils": "https://assets.nhle.com/logos/nhl/svg/NJD_dark.svg",
    "New York Islanders": "https://assets.nhle.com/logos/nhl/svg/NYI_dark.svg",
    "New York Rangers": "https://assets.nhle.com/logos/nhl/svg/NYR_dark.svg",
    "Ottawa Senators": "https://assets.nhle.com/logos/nhl/svg/OTT_dark.svg",
    "Philadelphia Flyers": "https://assets.nhle.com/logos/nhl/svg/PHI_dark.svg",
    "Pittsburgh Penguins": "https://assets.nhle.com/logos/nhl/svg/PIT_dark.svg",
    "San Jose Sharks": "https://assets.nhle.com/logos/nhl/svg/SJS_dark.svg",
    "Seattle Kraken": "https://assets.nhle.com/logos/nhl/svg/SEA_dark.svg",
    "St. Louis Blues": "https://assets.nhle.com/logos/nhl/svg/STL_dark.svg",
    "Tampa Bay Lightning": "https://assets.nhle.com/logos/nhl/svg/TBL_dark.svg",
    "Toronto Maple Leafs": "https://assets.nhle.com/logos/nhl/svg/TOR_dark.svg",
    "Utah Hockey Club": "https://assets.nhle.com/logos/nhl/svg/UTA_dark.svg",
    "Vancouver Canucks": "https://assets.nhle.com/logos/nhl/svg/VAN_dark.svg",
    "Vegas Golden Knights": "https://assets.nhle.com/logos/nhl/svg/VGK_dark.svg",
    "Washington Capitals": "https://assets.nhle.com/logos/nhl/svg/WSH_dark.svg",
    "Winnipeg Jets": "https://assets.nhle.com/logos/nhl/svg/WPG_dark.svg",

    // MLB Teams (ESPN)
    "Arizona Diamondbacks": "https://a.espncdn.com/i/teamlogos/mlb/500/ari.png",
    "Atlanta Braves": "https://a.espncdn.com/i/teamlogos/mlb/500/atl.png",
    "Baltimore Orioles": "https://a.espncdn.com/i/teamlogos/mlb/500/bal.png",
    "Boston Red Sox": "https://a.espncdn.com/i/teamlogos/mlb/500/bos.png",
    "Chicago Cubs": "https://a.espncdn.com/i/teamlogos/mlb/500/chc.png",
    "Chicago White Sox": "https://a.espncdn.com/i/teamlogos/mlb/500/chw.png",
    "Cincinnati Reds": "https://a.espncdn.com/i/teamlogos/mlb/500/cin.png",
    "Cleveland Guardians": "https://a.espncdn.com/i/teamlogos/mlb/500/cle.png",
    "Colorado Rockies": "https://a.espncdn.com/i/teamlogos/mlb/500/col.png",
    "Detroit Tigers": "https://a.espncdn.com/i/teamlogos/mlb/500/det.png",
    "Houston Astros": "https://a.espncdn.com/i/teamlogos/mlb/500/hou.png",
    "Kansas City Royals": "https://a.espncdn.com/i/teamlogos/mlb/500/kc.png",
    "Los Angeles Angels": "https://a.espncdn.com/i/teamlogos/mlb/500/laa.png",
    "Los Angeles Dodgers": "https://a.espncdn.com/i/teamlogos/mlb/500/lad.png",
    "Miami Marlins": "https://a.espncdn.com/i/teamlogos/mlb/500/mia.png",
    "Milwaukee Brewers": "https://a.espncdn.com/i/teamlogos/mlb/500/mil.png",
    "Minnesota Twins": "https://a.espncdn.com/i/teamlogos/mlb/500/min.png",
    "New York Mets": "https://a.espncdn.com/i/teamlogos/mlb/500/nym.png",
    "New York Yankees": "https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png",
    "Oakland Athletics": "https://a.espncdn.com/i/teamlogos/mlb/500/oak.png",
    "Philadelphia Phillies": "https://a.espncdn.com/i/teamlogos/mlb/500/phi.png",
    "Pittsburgh Pirates": "https://a.espncdn.com/i/teamlogos/mlb/500/pit.png",
    "San Diego Padres": "https://a.espncdn.com/i/teamlogos/mlb/500/sd.png",
    "San Francisco Giants": "https://a.espncdn.com/i/teamlogos/mlb/500/sf.png",
    "Seattle Mariners": "https://a.espncdn.com/i/teamlogos/mlb/500/sea.png",
    "St. Louis Cardinals": "https://a.espncdn.com/i/teamlogos/mlb/500/stl.png",
    "Tampa Bay Rays": "https://a.espncdn.com/i/teamlogos/mlb/500/tb.png",
    "Texas Rangers": "https://a.espncdn.com/i/teamlogos/mlb/500/tex.png",
    "Toronto Blue Jays": "https://a.espncdn.com/i/teamlogos/mlb/500/tor.png",
    "Washington Nationals": "https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png",

    // NBA Teams (ESPN)
    "Atlanta Hawks": "https://a.espncdn.com/i/teamlogos/nba/500/atl.png",
    "Boston Celtics": "https://a.espncdn.com/i/teamlogos/nba/500/bos.png",
    "Brooklyn Nets": "https://a.espncdn.com/i/teamlogos/nba/500/bkn.png",
    "Charlotte Hornets": "https://a.espncdn.com/i/teamlogos/nba/500/cha.png",
    "Chicago Bulls": "https://a.espncdn.com/i/teamlogos/nba/500/chi.png",
    "Cleveland Cavaliers": "https://a.espncdn.com/i/teamlogos/nba/500/cle.png",
    "Dallas Mavericks": "https://a.espncdn.com/i/teamlogos/nba/500/dal.png",
    "Denver Nuggets": "https://a.espncdn.com/i/teamlogos/nba/500/den.png",
    "Detroit Pistons": "https://a.espncdn.com/i/teamlogos/nba/500/det.png",
    "Golden State Warriors": "https://a.espncdn.com/i/teamlogos/nba/500/gs.png",
    "Houston Rockets": "https://a.espncdn.com/i/teamlogos/nba/500/hou.png",
    "Indiana Pacers": "https://a.espncdn.com/i/teamlogos/nba/500/ind.png",
    "Los Angeles Clippers": "https://a.espncdn.com/i/teamlogos/nba/500/lac.png",
    "Los Angeles Lakers": "https://a.espncdn.com/i/teamlogos/nba/500/lal.png",
    "Memphis Grizzlies": "https://a.espncdn.com/i/teamlogos/nba/500/mem.png",
    "Miami Heat": "https://a.espncdn.com/i/teamlogos/nba/500/mia.png",
    "Milwaukee Bucks": "https://a.espncdn.com/i/teamlogos/nba/500/mil.png",
    "Minnesota Timberwolves": "https://a.espncdn.com/i/teamlogos/nba/500/min.png",
    "New Orleans Pelicans": "https://a.espncdn.com/i/teamlogos/nba/500/no.png",
    "New York Knicks": "https://a.espncdn.com/i/teamlogos/nba/500/ny.png",
    "Oklahoma City Thunder": "https://a.espncdn.com/i/teamlogos/nba/500/okc.png",
    "Orlando Magic": "https://a.espncdn.com/i/teamlogos/nba/500/orl.png",
    "Philadelphia 76ers": "https://a.espncdn.com/i/teamlogos/nba/500/phi.png",
    "Phoenix Suns": "https://a.espncdn.com/i/teamlogos/nba/500/phx.png",
    "Portland Trail Blazers": "https://a.espncdn.com/i/teamlogos/nba/500/por.png",
    "Sacramento Kings": "https://a.espncdn.com/i/teamlogos/nba/500/sac.png",
    "San Antonio Spurs": "https://a.espncdn.com/i/teamlogos/nba/500/sa.png",
    "Toronto Raptors": "https://a.espncdn.com/i/teamlogos/nba/500/tor.png",
    "Utah Jazz": "https://a.espncdn.com/i/teamlogos/nba/500/utah.png",
    "Washington Wizards": "https://a.espncdn.com/i/teamlogos/nba/500/wsh.png",

    // NFL Teams (ESPN)
    "Arizona Cardinals": "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
    "Atlanta Falcons": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
    "Baltimore Ravens": "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
    "Buffalo Bills": "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
    "Carolina Panthers": "https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
    "Chicago Bears": "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
    "Cincinnati Bengals": "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
    "Cleveland Browns": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
    "Dallas Cowboys": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
    "Denver Broncos": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
    "Detroit Lions": "https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
    "Green Bay Packers": "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
    "Houston Texans": "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png",
    "Indianapolis Colts": "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
    "Jacksonville Jaguars": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
    "Kansas City Chiefs": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
    "Las Vegas Raiders": "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png",
    "Los Angeles Chargers": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
    "Los Angeles Rams": "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
    "Miami Dolphins": "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
    "Minnesota Vikings": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
    "New England Patriots": "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
    "New Orleans Saints": "https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
    "New York Giants": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
    "New York Jets": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
    "Philadelphia Eagles": "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
    "Pittsburgh Steelers": "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
    "San Francisco 49ers": "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
    "Seattle Seahawks": "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png",
    "Tampa Bay Buccaneers": "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
    "Tennessee Titans": "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
    "Washington Commanders": "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",

    // Soccer Teams (ESPN)
    "Real Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/86.png",
    "Barcelona": "https://a.espncdn.com/i/teamlogos/soccer/500/83.png",
    "Atletico Madrid": "https://a.espncdn.com/i/teamlogos/soccer/500/1068.png",
    "Manchester United": "https://a.espncdn.com/i/teamlogos/soccer/500/360.png",
    "Manchester City": "https://a.espncdn.com/i/teamlogos/soccer/500/382.png",
    "Liverpool": "https://a.espncdn.com/i/teamlogos/soccer/500/364.png",
    "Arsenal": "https://a.espncdn.com/i/teamlogos/soccer/500/359.png",
    "Chelsea": "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
    "Tottenham Hotspur": "https://a.espncdn.com/i/teamlogos/soccer/500/367.png",
    "Juventus": "https://a.espncdn.com/i/teamlogos/soccer/500/111.png",
    "AC Milan": "https://a.espncdn.com/i/teamlogos/soccer/500/103.png",
    "Inter Milan": "https://a.espncdn.com/i/teamlogos/soccer/500/110.png",
    "Bayern Munich": "https://a.espncdn.com/i/teamlogos/soccer/500/132.png",
    "Borussia Dortmund": "https://a.espncdn.com/i/teamlogos/soccer/500/124.png",
    "Paris Saint-Germain": "https://a.espncdn.com/i/teamlogos/soccer/500/160.png",

    // CFL Teams (ESPN CDN)
    "Edmonton Elks": "https://a.espncdn.com/i/teamlogos/cfl/500/edm.png",
    "Calgary Stampeders": "https://a.espncdn.com/i/teamlogos/cfl/500/cgy.png",
    "Saskatchewan Roughriders": "https://a.espncdn.com/i/teamlogos/cfl/500/ssk.png",
    "Winnipeg Blue Bombers": "https://a.espncdn.com/i/teamlogos/cfl/500/wpg.png",
    "BC Lions": "https://a.espncdn.com/i/teamlogos/cfl/500/bc.png",
    "Toronto Argonauts": "https://a.espncdn.com/i/teamlogos/cfl/500/tor.png",
    "Hamilton Tiger-Cats": "https://a.espncdn.com/i/teamlogos/cfl/500/ham.png",
    "Ottawa Redblacks": "https://a.espncdn.com/i/teamlogos/cfl/500/ott.png",
    "Montreal Alouettes": "https://a.espncdn.com/i/teamlogos/cfl/500/mtl.png",

    // WHL Teams
    "Calgary Hitmen": "https://assets.leaguestat.com/whl/logos/207.png",
    "Edmonton Oil Kings": "https://assets.leaguestat.com/whl/logos/209.png",
    "Lethbridge Hurricanes": "https://assets.leaguestat.com/whl/logos/211.png",
    "Medicine Hat Tigers": "https://assets.leaguestat.com/whl/logos/212.png",
    "Prince George Cougars": "https://assets.leaguestat.com/whl/logos/213.png",
    "Prince Albert Raiders": "https://assets.leaguestat.com/whl/logos/214.png",
    "Red Deer Rebels": "https://assets.leaguestat.com/whl/logos/215.png",
    "Swift Current Broncos": "https://assets.leaguestat.com/whl/logos/216.png",
    "Kamloops Blazers": "https://assets.leaguestat.com/whl/logos/217.png",
    "Vancouver Giants": "https://assets.leaguestat.com/whl/logos/218.png",
    "Victoria Royals": "https://assets.leaguestat.com/whl/logos/219.png",
    "Kelowna Rockets": "https://assets.leaguestat.com/whl/logos/220.png",
    "Portland Winterhawks": "https://assets.leaguestat.com/whl/logos/221.png",
    "Seattle Thunderbirds": "https://assets.leaguestat.com/whl/logos/222.png",
    "Spokane Chiefs": "https://assets.leaguestat.com/whl/logos/223.png",
    "Tri-City Americans": "https://assets.leaguestat.com/whl/logos/224.png",
    "Everett Silvertips": "https://assets.leaguestat.com/whl/logos/225.png",
    "Winnipeg Ice": "https://assets.leaguestat.com/whl/logos/226.png",
    "Moose Jaw Warriors": "https://assets.leaguestat.com/whl/logos/227.png",
    "Saskatoon Blades": "https://assets.leaguestat.com/whl/logos/228.png",
    "Regina Pats": "https://assets.leaguestat.com/whl/logos/229.png",
    "Brandon Wheat Kings": "https://assets.leaguestat.com/whl/logos/230.png",
};

const LEAGUE_LOGOS = {
    "NHL": "🏒",
    "MLB": "⚾",
    "NBA": "🏀",
    "NFL": "🏈",
    "La Liga": "⚽",
    "Premier League": "⚽",
    "Bundesliga": "⚽",
    "Serie A": "⚽",
    "Ligue 1": "⚽",
    "MLS": "⚽",
    "CFL": "🏈",
    "CEBL": "🏀",
    "WHL": "🏒",
    "OHL": "🏒",
    "QMJHL": "🏒"
};

// Fallback colors per team (used when logo fails to load)
const TEAM_COLORS = {
    // NHL
    "Edmonton Oilers": "#FF4C00", "Calgary Flames": "#C8102E", "Vancouver Canucks": "#00843D",
    "Winnipeg Jets": "#004C97", "Ottawa Senators": "#C8102E", "Toronto Maple Leafs": "#00205B",
    "Montreal Canadiens": "#AF1E2D", "Pittsburgh Penguins": "#FCB514",
    // WHL
    "Edmonton Oil Kings": "#003087", "Calgary Hitmen": "#C8102E", "Red Deer Rebels": "#CE1126",
    "Lethbridge Hurricanes": "#003087", "Medicine Hat Tigers": "#FF6600",
    "Prince George Cougars": "#005028", "Prince Albert Raiders": "#003087",
    "Swift Current Broncos": "#003087", "Kamloops Blazers": "#C8102E",
    "Vancouver Giants": "#C8102E", "Victoria Royals": "#003087", "Kelowna Rockets": "#C8102E",
    "Portland Winterhawks": "#C8102E", "Seattle Thunderbirds": "#005EB8",
    "Spokane Chiefs": "#C8102E", "Tri-City Americans": "#C8102E",
    "Everett Silvertips": "#005028", "Winnipeg Ice": "#001F5B",
    "Moose Jaw Warriors": "#C8102E", "Saskatoon Blades": "#FFD700",
    "Regina Pats": "#003087", "Brandon Wheat Kings": "#003087",
};

function getTeamLogo(teamName) {
    return TEAM_LOGO_URLS[teamName] || null;
}

function getLeagueLogo(leagueName) {
    return LEAGUE_LOGOS[leagueName] || "🏟️";
}

function getTeamColor(teamName) {
    return TEAM_COLORS[teamName] || "#0a84ff";
}
